### ISSUE TITLE
Update to TypeScript

### ISSUE THREAD

**Issue by MarkPieszak** [MarkPieszak/aspnetcore-Vue-starter#1]

**Comment by vip32** [comment]
or maybe create a separate starter, as ts is not that popular (yet?) in the vuejs community.

**Comment by anderly** [comment]
Possible guide using vue-ts-loader: https://herringtondarkholme.github.io/2016/10/03/vue2-ts2/

**Comment by MarkPieszak** [comment]
How do you guys feel about? @anderly @vip32 
I mean personally I <3 TypeScript, I'm sure people will change their minds eventually.

Should we leave it at ES6 for now, and maybe just have a small note on TS usage,
Or go full-on TypeScript?

**Comment by vip32** [comment]
i also love TS, however not convinced to use it together with vuejs. it's not as nicely integrated as with angular nowadays. also the vuejs community mostly seems to use es6. so if we do TS it should best be another template (choice).

**Comment by vip32** [comment]
maybe if this js template is done we instead can work on a more advanced vuejs template with:
- typescript
- bootstrap + fonts + icons
- full server side rendering
- unit + e2e tests

**Comment by anderly** [comment]
I think separate typescript template is a good idea. I've got a few more minor changes to this one (missed the namespace change in a few files, etc), but then we could move on to TS template.

**Comment by alexsandro-xpt** [comment]
Separate typescript template is better, I guess, this should be ASP NET Core for VueJS and not VueJS for ASP NET Core.

VueJS side should be ever mantening the project defaults.

**Comment by MarkPieszak** [comment]
So Steve Sanderson from the aspnet team took this template and updated it to TypeScript (with a few other tweaks) but you can find it with `npm i -g aspnetcore-spa yo` then `yo aspnetcore-spa` and install the Vue template. I think he merged it like an hour ago, so it might not be updated onto yeoman just yet.
