### ISSUE TITLE
Add new project with visual studio

### ISSUE THREAD

**Issue by ArthNRick** [MarkPieszak/aspnetcore-Vue-starter#109]
In readme.md you said: "his repo contains an ASP.NET Core + Vue.js 2 starter template (VS2017 or command line)", but I did not find a way to add the template to VS2017, how should I proceed to create the template? project from visual studio?

**Comment by MarkPieszak** [comment]
Use dotnet new to get it!

```ts
dotnet new -i aspnetcore-vuejs
```

**Comment by Nordes** [comment]
Open the template project and then in the menu you can export the project as a template project.

**Comment by ArthNRick** [comment]
Thank you @Nordes , it worked.

**Comment by ArthNRick** [comment]
Export project as template it worked
