### ISSUE TITLE
some updates 

### ISSUE THREAD

**Issue by vip32** [MarkPieszak/aspnetcore-Vue-starter#11]
Hi @MarkPieszak ,

i started some work in my fork of this repo. main goal is to bring it more up to par with the other aspnetcore starters (knockout/react)
https://github.com/vip32/aspnetcore-Vue-starter

- same webpack/npm setup
- some folder structure
- site.css added
- bootstrap added
- vs2017 csproj
- SampleDataController like other starters

next thing:
- bring the demo app alive with bootstrap
- typescript
- dotnet new capability

for now i have removed the server side rendering, not so convinced it is needed in a non advanced starter. also vue apps should already load fast (due to footprint), compared to ng. for crawlers it is interesting of course.

**Comment by MarkPieszak** [comment]
Just looked at the changes and they look great! Nice job! :100: 
Did you want to make a PR so we can implement everything or not yet?

**Comment by vip32** [comment]
yes let me submit a PR now, then i will continue on the app itself (so it works the same as the other starters)

**Comment by MarkPieszak** [comment]
Merged! 👍👍
