### ISSUE TITLE
Use axios in place of vue-resource

### ISSUE THREAD

**Issue by anderly** [MarkPieszak/aspnetcore-Vue-starter#14]
Since vue-resource is retiring (https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4#.lu29ki141), thought this might be a logical next step to get this template up to par.

I've forked the repo and will submit this back as a PR if you're good with that.

I'll even set Vue.prototype.$http = axios to minimize disruption.

**Comment by MarkPieszak** [comment]
Thanks again!

**Comment by anderly** [comment]
Sure thing! I guess this might also close #5 as well since the WebAPI sample is now working.
