### ISSUE TITLE
make available through 'dotnet new'

### ISSUE THREAD

**Issue by vip32** [MarkPieszak/aspnetcore-Vue-starter#19]
make this template usable with 'dotnet new'. like the other starter templates.
what needs to be done to have this capability?

![image](https://cloud.githubusercontent.com/assets/164303/23277363/dabcd534-fa0d-11e6-841b-f9d09e6d36e8.png)

https://blogs.msdn.microsoft.com/dotnet/2017/04/02/how-to-create-your-own-templates-for-dotnet-new/

**Comment by vip32** [comment]
make this template usable with 'dotnet new'. like the other starter templates.
what needs to be done to have this capability?

**Comment by MarkPieszak** [comment]
Totally unrelated: Added you and @anderly as Collaborators by the way! 🥇 
You guys rock!

**Comment by vip32** [comment]
oh nice, that makes things easier :)

**Comment by vip32** [comment]
@MarkPieszak Do you have experience with these 'dotnet new' templates?

**Comment by MarkPieszak** [comment]
I was actually researching it since I was going to publish the .NET Angular one shortly after I update it to ng4.x, hadn't published just yet. 

This was a great article on it I had bookmarked: http://pioneercode.com/post/how-to-create-a-dot-net-new-project-template-in-dot-net-core

**Comment by vip32** [comment]
more infos https://github.com/dotnet/templating

**Comment by miseeger** [comment]
Hi guys just want to say: "Thank you for this !!!" 👍 Looking forward to having it officially available via "dotnet new" 😎

**Comment by MarkPieszak** [comment]
Thank you, glad it's helping you get going! 

I'll get the dotnet template out there this week, finally settling in after a cross-country move 👍

**Comment by nbarbettini** [comment]
Any progress on this?

**Comment by mika76** [comment]
I have this working with this repo, but the structure needs to change (move pretty much everything into a "content" folder) - would this change be ok? Should I make a pull request?

**Comment by MarkPieszak** [comment]
We're all set! Merged via 4f6f10e
