### ISSUE TITLE
Project changes to sync with aspnet/JavaScriptServices templates

### ISSUE THREAD

**Issue by anderly** [MarkPieszak/aspnetcore-Vue-starter#20]
- Change .csproj name to VueSpa.csproj or Vue2Spa.csproj like the others (Angular2Spa.csproj, KnockoutSpa.csproj, ReactSpa.csproj, etc.)
- ~~Add VueSpa.xproj for backward compatibility with MSBuild~~
- ~~Add back project.json for VS2015 compatibility (the other Spa templates have this as well)~~
- Change default namespace to either VueSpa or WebApplicationBasic (example here: https://github.com/aspnet/JavaScriptServices/blob/dev/templates/KnockoutSpa/Controllers/HomeController.cs)
- Sync up .csproj like here: https://github.com/aspnet/JavaScriptServices/blob/dev/templates/Angular2Spa/Angular2Spa.csproj
    - Simplify/reduce package references
    - Add `<Content Remove="ClientApp\**" />`
    - Add `<Target Name="RunWebpack" AfterTargets="ComputeFilesToPublish">`

**Comment by vip32** [comment]
Hi @anderly ,

I would advise not to provide any backward support, VS2017/msbuild is the way forward and the only platform that will get 'real' .net core support by MS. we should not make this more complex than needed. xproj + project.json are history.

will you provide a PR for the others points (so we will not work one the same again), otherwise i can work on it.

**Comment by anderly** [comment]
Ok, @vip32, I updated the list above and dropped the xproj and project.json. Yes, I can provide a PR for these.

**Comment by anderly** [comment]
@vip32, @MarkPieszak you guys cool with the other proposed changes listed above?

**Comment by MarkPieszak** [comment]
Everything looks great to me Adam! 👍 👍 
Yeah I was going to upgrade the .NET & Angular solution I have as well to csproj after Steve updated his. I supposed VS2015 is history now!

**Comment by anderly** [comment]
Ok, I added these changes to PR #17.
