### ISSUE TITLE
It's could be compatible with webpack Vue CLI template

### ISSUE THREAD

**Issue by alexsandro-xpt** [MarkPieszak/aspnetcore-Vue-starter#26]
The directory structure created by `vue-cli` is diferent with this actual structure.

Is imposible to make it identical?

Take a look:
http://vuejs-templates.github.io/webpack/structure.html
https://github.com/vuejs-templates/webpack/tree/master/template

**Comment by vip32** [comment]
We choose to have same structure as the other aspnet core starters
