### ISSUE TITLE
error running `dotnet new --install Microsoft.AspNetCore.SpaTemplates.Vue2Js`

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [MarkPieszak/aspnetcore-Vue-starter#28]
Hi,

I tried: `dotnet new --install Microsoft.AspNetCore.SpaTemplates.Vue2Js`

got:

`Error: Package "Microsoft.AspNetCore.SpaTemplates.Vue2Js" is not a valid package specification`

Please are there any prerequisites needed?

**Comment by vip32** [comment]
Sorry, this is still being worked on. This feature is marked as TODO

**Comment by vip32** [comment]
See #19

**Comment by alexsandro-xpt** [comment]
So, it's don't work yet.... Right?

**Comment by MarkPieszak** [comment]
@alexsandro-xpt Yea not yet, we haven't added it to the `dotnet template` so that it can be downloaded that way, for now you need to just fork & clone the repo to get it going. Apologies!

**Comment by alexsandro-xpt** [comment]
All right, please tell us when it is done! Thanks!!

**Comment by mika76** [comment]
It seems the MS gang are stopping including the original Vue template in their package (see [this](https://github.com/aspnet/Announcements/issues/289)) so maybe this could become the "official" vue starter project?

**Comment by MarkPieszak** [comment]
I think so! :+1: 

I'm guessing I can close this issue out now?
If there's anything else missing to show how to install everything from the README, just let me know.

You rock @mika76 🥇

**Comment by MarkPieszak** [comment]
@mika76 For some reason actually, I can't get `dotnet new --install Microsoft.AspNetCore.SpaTemplates.Vue2Js` to work on a new machine either.

Trying to figure out what's missing

**Comment by mika76** [comment]
Sorry guys, I had forgotten to update the readme file. I will update (I see I have conflicts)

but the main issue is the nuget package you're installing. The command should be 
```
dotnet new -i aspnetcore-vuejs
```
and then you can do
```
dotnet new vuejs
```

The main nuget package is at https://www.nuget.org/packages/aspnetcore-vuejs/

**Comment by MarkPieszak** [comment]
We're all set! Merged via 4f6f10e
