### ISSUE TITLE
`dotnet restore` not working

### ISSUE THREAD

**Issue by nathanchere** [MarkPieszak/aspnetcore-Vue-starter#30]
> Instructions:
> 1) Clone this repo
> 2) At the repo's root directory run dotnet restore
> ...

Don't you need a project.json for that? As it stands you'll only get an error message that there's no project to restore.

**Comment by vip32** [comment]
what error do you get. project.json is not needed as we use the new csproj

**Comment by nathanchere** [comment]
warn : The folder '/home/username/src/dotnetcorevue' does not contain a project to restore.

It doesn't recognise the csproj if I specify to restore from that specifically.

Have  dotnetcore CLI 1.1.0-7 installed. Will update if I work out what the problem is.
