### ISSUE TITLE
Production build/Publish/webpack.config.vendor.js

### ISSUE THREAD

**Issue by StormGoth** [MarkPieszak/aspnetcore-Vue-starter#31]
Hello,

when trying to publish this project I get the usual "`Unexpected token: name (b) [vendor.js:20623,5]`" from UglifyJS indicating that it wasn't translated to es2015.

So I copied the content of webpack.config.js to webpack.config.vendor.js (since it seemed to have the correct 'isDevBuild' flag and uses the babel preprocessor), but now the stuff from ClientApp isn't included when published:
`Exception: Call to Node module failed with error: Prerendering failed because of error: Error: ENOENT: no such file or directory, open 'C:\inetpub\wwwroot\...\ClientApp\boot-server.js'`

After manually copying this directory (sorry, new to webpack/babel, no idea how to reference the bundled/ processed js files) I got the error:` Cannot find module 'aspnet-prerendering'` - seems logical since it is only included as a devDependency in package.json :)

Since I don't know what I'm doing I'll stop here :)

**Comment by erw13n** [comment]
I got same issue, remove "style-loader" from vendor entry will solve the issue, but CSS will not load correctly.

**Comment by MarkPieszak** [comment]
Strange that this issue randomly sprung up, removing style-loader doesn't break any other functionality? 
If everything else works with that removed, that works for me 👍 

Want to submit a quick lil PR for that fix @erw13n ? Thanks for figuring that one out!

**Comment by erw13n** [comment]
OK, sure.
