### ISSUE TITLE
Stuck on loading screen.

### ISSUE THREAD

**Issue by thompsonryan** [MarkPieszak/aspnetcore-Vue-starter#32]
I cloned the project, did a `dotnet restore` successfully, and an `npm install` successfully.  Then running the application both from the CLI and from withing Visual Studio, I am getting just the loading screen.  The console gives a 404 for the following files:
```
http://localhost:5000/dist/site.css 
http://localhost:5000/dist/main.js 
```

**Comment by MarkPieszak** [comment]
Can you do a quick `npm run dev` and see if that handles it better? That sets the ASPNETCORE_ENVIRONMENT variable for you as well.

**Comment by thompsonryan** [comment]
That does the trick.  I assumed incorrectly that `dotnet run` would be the sure fire way to run it.

**Comment by MarkPieszak** [comment]
Great! 👍 Since we need to run webpack first unfortunately we need those assets before all the other magic can start.
