### ISSUE TITLE
what is the correct way to add new NuGet packages?

### ISSUE THREAD

**Issue by LookRain** [MarkPieszak/aspnetcore-Vue-starter#35]
I tried to install NuGet packages by right clicking on Dependencies inside VS2017, the error shown is:
`Error		Package restore failed. Rolling back package changes for 'Vue2Spa'.`
  
 I also tried to add the dependency inside the 'Vue2Spa.csproj' file. This method worked but I feel it is still not the best way to do it.

I could not find any other information elsewhere, so I'm here asking what is the best way to add new NuGet packages? Thanks.

**Comment by MarkPieszak** [comment]
Did you ever get this working? It might be totally different now with dotnet core 2.0.
Closing this out, but let me know!
