### ISSUE TITLE
npm install fails on typescript

### ISSUE THREAD

**Issue by yoyoys** [MarkPieszak/aspnetcore-Vue-starter#37]
`
npm ERR! path ...\aspnet-vue\node_modules\typescript
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '...\aspnet-vue\node_modules\typescript' -> '...\aspnet-vue\node_modules\.typescript.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.`

I got this message from npm.
i tried to change the typescript to 2.4.1, and this error gone, but i don't know why.

and why i need typescript in this project? thanks

**Comment by MarkPieszak** [comment]
That must be an old remanent from when the project was doing everything in Typescript, you should be able to remove it and it work fine! 

Maybe you can make a quick PR with it removed if it works well afterwards? Let me know!
Cheers.

**Comment by yoyoys** [comment]
I Just remove that package, and it works fine for sure 😄
