### ISSUE TITLE
Do you have plans for sass or less support?

### ISSUE THREAD

**Issue by yoyoys** [MarkPieszak/aspnetcore-Vue-starter#40]
I tried to use some paid template to this project,
and i'd like to use bootstrap4 with sass or bootstrap3 with less,
which would you like? 
If done, i wanna contribute for this project

**Comment by konraddysput** [comment]
Ok - so to use sass/less you have to have compiler to it ( for example if you use Visual Studio there is add onn web compiler that compile all scss files into min css file). Last time when i configured webpack in our company I saw that even webpack can compile scss/less into css. You can use scss or less right now without any help.

For your information - Im just a watcher on this project  - not developer

**Comment by MarkPieszak** [comment]
You just need to add the rules in your webpack config to set up scss transpiling. Something along the lines of the rules below should do the trick if you install those loaders as well.

    rules: [
      { test: /\.css$/, loader: ['to-string-loader', 'css-loader'] },
      { test: /\.scss$/, loaders: ['to-string-loader', 'css-loader', 'sass-loader'] }
    ]
