### ISSUE TITLE
Typescript support - getting started page

### ISSUE THREAD

**Issue by konraddysput** [MarkPieszak/aspnetcore-Vue-starter#41]
Hello,
today I downloaded and compiled project. In getting started page you write information about typescript support, but I dont think that your webpack script is ready for typescript support. Even if it is, vue in typescript require a lot cool libraries to work well - attributes, routing etc.

![image](https://user-images.githubusercontent.com/9386268/27984584-c658a9ac-63d9-11e7-89a1-55184bfd5c93.png)

Am I miss something or this starter isnt ready right now for typescript support ? (dont see any ts file)

BTW: Really nice job with this project.

thanks for your help

**Comment by yoyoys** [comment]
i'm not sure....but `dotnet new vue` present a vue template for typescript.

P.S. You need to run this first.
`dotnet new --install Microsoft.AspNetCore.SpaTemplates::*`

**Comment by MarkPieszak** [comment]
So we decided to stick with es6 as most of the Vue community seems to favor it, but Steve has an identical starter to this (just typescript instead) as yoyo was just saying.

If anyone wants to do a quick PR to get rid of that typescript text it'd be much appreciated! I originally had it in TS 🙈
