### ISSUE TITLE
bootstrap hamburger not expanding

### ISSUE THREAD

**Issue by JasonLiebgott** [MarkPieszak/aspnetcore-Vue-starter#43]
When you resize the viewport to hide the left gutter, the hamburger does not expand.

**Comment by MarkPieszak** [comment]
This change was done in the angular repo, but I imagine it'd be fairly similar to do the same thing here though! https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/372

**Comment by MarkPieszak** [comment]
Closed via #61 thanks to @billmastiffo 🤘🍻
