### ISSUE TITLE
I can not publish to IIS

### ISSUE THREAD

**Issue by jardelsobrinho** [MarkPieszak/aspnetcore-Vue-starter#44]
In visual studio it works perfectly, but when I try to publish to IIS it does not work. Displays the following error: ASP.NET: HTTP Error 500.19 - Internal Server Error 0x8007000d
I researched in several places but I could not solve.

**Comment by MarkPieszak** [comment]
Was this with the base repo? Did you ever solve this? Haven't ran into this one before.

**Comment by jardelsobrinho** [comment]
Unfortunately I could not get IIS to work with this project. I believe the problem may be some iss incopatibility with the server side redenring feature. Following this tutorial https://stu.ratcliffe.io/2017/07/20/vuejs-serverside-rendering-with-aspnet-core, everything worked out right up to the Session Server-Side Rendering session. If I configure it as it is in the tutorial to Server-Side Rendering, no iis does not work. I think it may be the same problem as your project.

**Comment by MarkPieszak** [comment]
https://github.com/MarkPieszak/aspnetcore-Vue-starter/commit/ef6ce477b5649695e45d41922925ba4d9e484f48

It could be the above `asp-prerender-module` tag that needs to be completely removed, as we're not doing SSR here. Can you give that a shot and see if it works?

**Comment by MarkPieszak** [comment]
This should be fine now, let me know if it's not working!
