### ISSUE TITLE
Doesn't work with VSCode

### ISSUE THREAD

**Issue by Dave3of5** [MarkPieszak/aspnetcore-Vue-starter#48]
Cloned the repo then in VSCode I ran start with debugging and it never ran.

I think you are missing the .vscode/* files.

**Comment by Dave3of5** [comment]
I see from your .gitignore you don't want to add these so please disregard.

**Comment by MarkPieszak** [comment]
We could add them in there if you had some working vscode files you wanted to make a PR and add to the repo? VSCode is the best 👍
