### ISSUE TITLE
Please update for ASP.NET Core 2

### ISSUE THREAD

**Issue by k3davis** [MarkPieszak/aspnetcore-Vue-starter#49]
It would be great if this were updated for the new version of ASP.NET Core and made available with the other new spa templates for angular/react in VS 2017 with ASP.NET Core installed.

**Comment by MarkPieszak** [comment]
Apologies, the Angular repo was just ported over (like so: https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/371) we'll have to get this one over to 2.0 asap as well!

**Comment by MarkPieszak** [comment]
@k3davis It's all set now via #50
