### ISSUE TITLE
Hot Module Reload doesn't seem to work

### ISSUE THREAD

**Issue by keithn** [MarkPieszak/aspnetcore-Vue-starter#51]
I just downloaded the repository, ran it, website came up fine, but any changes to files doesn't seem to update the website.

If I refresh the page, then the change appears

in the javascript console in chromeI have 

EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.

Which keeps counting up.

   ( Using Visual Studio 2017  15.3.2 )

**Comment by MarkPieszak** [comment]
Yeah we're looking into this one, there's some kind of issue that appeared with dotnet 2.0 that's causing HMR to not really load properly!

**Comment by keithn** [comment]
You've probably seen it.... but the pre packaged react project in visual studio 2017 has a HMR setup that works fine, I haven't had a look at what the differences are.

**Comment by MarkPieszak** [comment]
Yeah, I need to see what might be causing it here. Might be something in StartUp.cs I'm missing / or a file like that.

**Comment by MarkPieszak** [comment]
Might be that we need to get to 2.x of aspnet-webpack: `"aspnet-webpack": "^2.0.1",` can you give that a shot?

**Comment by keithn** [comment]
Yep, that worked.

**Comment by elucidsoft** [comment]
Thank god I found this solution, I've spent 3 days trying to figure this out...Never thought of upping the version of aspnet-webpack oddly enough...Can you please make this change to the branch?

**Comment by MarkPieszak** [comment]
Sure, I'll make the change now!

**Comment by canperk** [comment]
Dude you saved my day :)
