### ISSUE TITLE
Can't "easily" edit vue based assets in Visual Studio

### ISSUE THREAD

**Issue by WillFM** [MarkPieszak/aspnetcore-Vue-starter#53]
In VS2017, I don't see the ClientApp folder in The solution browser, making it difficult to work with the vue components.

I'm assuming because the ClientApp folder is marked for removal in the .csproj file:
```xml
  <Content Remove="ClientApp\**" />
```
Any suggestions (outside of toggling "show all files") on making them visible?

**Comment by MarkPieszak** [comment]
This seems like something strange that dotnet core 2.0 introduced (in combination with VS2017) as these were all working before.

If you get rid of that line in csproj, does it fix the issue?

**Comment by elucidsoft** [comment]
I see the ClientApp folder just fine, I have VS 2017 15.3.2 installed.

**Comment by WillFM** [comment]
Looks like I jumped the gun on opining the bug. It appears the reason why the folder was not shown was because the folder contents was empty. (I had cleared it out, to replace it with my own files).

Sorry for the confusion.
