### ISSUE TITLE
Adding Breakpoints In Visual Studio?

### ISSUE THREAD

**Issue by schoening** [MarkPieszak/aspnetcore-Vue-starter#56]
Has anyone been able to add breakpoints to .js or .vue files using Visual Studio?

**Comment by MarkPieszak** [comment]
It should have VS Code debugging built-in, but I'd recommend using VSCode, or ideally the Chrome Debugger.

VS's integration with Chrome for debugging doesn't have a concept of source files changing during a debugging session, so you will have to disconnect and reconnect after editing a file. So, even if you had this working, it wouldn't be ideal (until maybe VS gets some updates to handle this better). 

Hope that helps!
