### ISSUE TITLE
PackageTargetFallback and AssetTargetFallback cannot be used together

### ISSUE THREAD

**Issue by JingYenLoh** [MarkPieszak/aspnetcore-Vue-starter#57]
Hi, I'm running .NET Core 2.0.0 stable. When I run ```dotnet restore``` on a freshly cloned project, I get the following error:

```
error NU1003: PackageTargetFallback and AssetTargetFallback cannot be used together.
Remove PackageTargetFallback(deprecated) references from the project environment.
```

I tried deleting the ```PackageTargetFallback``` property from ```Vue2Spa.csproj``` as suggested in [this post](https://stackoverflow.com/a/45569379) from stackoverflow and it works.

**Comment by GuilhermeHideki** [comment]
@MarkPieszak would you accept an PR addressing that?

**Comment by MarkPieszak** [comment]
Of course! @GuilhermeHideki I think someone just posted one via #59 
We should be all set now!

Any other great PRs you have in mind, let me know!
