### ISSUE TITLE
How to config webpack.config.js to support less,scss,sass ?

### ISSUE THREAD

**Issue by carldai0106** [MarkPieszak/aspnetcore-Vue-starter#65]
Hi ,
   I do not know how to config it to support less,scss,sass.
   And I want write (embedded) style (scss,less,sass) in *.vue file.
   Could you give me some tips.

**Comment by MarkPieszak** [comment]
Hey there, it'd be setup exactly the same way it usually is with webpack & vue, check out the Vue documentation for more info there!

It'd just be some rules[] you need to add for /less/ /scss/ or whichever you'd like to use :)

Hope that helps!
