### ISSUE TITLE
Question: Can this work with .NET Standard

### ISSUE THREAD

**Issue by iang0ld** [MarkPieszak/aspnetcore-Vue-starter#66]
We can't move to Core yet due to some of our libraries?

**Comment by MarkPieszak** [comment]
It couldn't work in the current way it's setup, you'd have to just manually put in a Vue project and do everything in command-line until you're able to move to Core. The previous dotnets can't handle communication between Node / webpack processes the way that Core can unfortunately!

Hope that helps.

**Comment by iang0ld** [comment]
Thanks Mark,

I understand now.  I think we will have to just drop in the js file and work with that initially.

Thanks
Ian
