### ISSUE TITLE
More info on main.js and vendor.js

### ISSUE THREAD

**Issue by kvigor** [MarkPieszak/aspnetcore-Vue-starter#68]
@MarkPieszak I just wanted to know the significance of the main.js and vendor.js files.  These are huge files and I'm not quite sure what they are doing yet, adding an explanation to the wiki or readme would be awesome.

**Comment by MarkPieszak** [comment]
Hey @kvigor 
Are you in development mode? The files will be huge then, mainly because of all the sourcemaps and no minifications/uglify'ing happening. 

Try building production bundles and you'll see they're much lower!
