### ISSUE TITLE
Adding components to _Layout.cshtml

### ISSUE THREAD

**Issue by kvigor** [MarkPieszak/aspnetcore-Vue-starter#69]
Is it possible to render a component outside the main app div? Trying it doesn't seem to work and I would like to add a component to my _Layout.cshtml

**Comment by MarkPieszak** [comment]
I think you'd have to just move your main app component to a more global location, that way you can inject things wherever you'd like. 

You could just have the main app component be immediately inside of the entire `<body>` (in _layout). Then you could do whatever you'd like.

Hope that helps!

**Comment by kvigor** [comment]
Oh sweet!  I'll give that a try and post my findings.  _Thanks._
