### ISSUE TITLE
If I remove bootstrap no vendor.css is created

### ISSUE THREAD

**Issue by axi71** [MarkPieszak/aspnetcore-Vue-starter#70]
I've removed all dependencies of bootstrap.css because I don't want to use it:
from package.json
from webpack.config.vendor.js
did all from scratch after cloning repository.
Afterwards:
npm install
dotnet run
no vendor.css has been created in wwwroot/dist
Did I miss something?

**Comment by MarkPieszak** [comment]
Can you run `npm run dev` and see if that builds and runs everything for you?
That is what actually runs the webpack command, dotnet run might not be executing it for you.

Hope that helps!
