### ISSUE TITLE
Issues running program due to version conflict with dotnet

### ISSUE THREAD

**Issue by skozzii** [MarkPieszak/aspnetcore-Vue-starter#72]
I followed instructions to set up the program, but could not get anything to display until I went into global.json and deleted "  "sdk": { "version": "2.0.0" }" then everything works fine.

I am still new to all this, do I fork and then make a change, to the deleted file, or is there a reason that we want some version number in there.  It would also not load with   "sdk": { "version": "^2.0.0" } modified.

Perhaps I had done something else wrong, but I tried on both my computers and encountered the same issue.

Thanks,

Steve

**Comment by MarkPieszak** [comment]
Thanks @skozzii Steve!

I didn't have any problems, but this might be an issue with VS2017 (I'm guessing that's what you were using). That was in there when we were between 1.x and 2.x of aspnet core.

I pushed up the change to remove that file, we should be all set! :+1:
