### ISSUE TITLE
Update to bootstrap 4

### ISSUE THREAD

**Issue by Nordes** [MarkPieszak/aspnetcore-Vue-starter#75]
Since the Bootstrap 4 is finally available, it would be nice to have the latest version within the project.

**Comment by Nordes** [comment]
@MarkPieszak I have a branch with WIP regarding the upgrades of all the packages within this template. I was able to setup the Bootstrap 4 / etc. I've also added the active link (there was missing code).

**Comment by MarkPieszak** [comment]
It should work for anything under `/ClientApp` folder.
Does the file name end with `.spec.ts` ?

**Comment by MarkPieszak** [comment]
It might be a great idea for us to upgrade now that it's out of beta!
If you have a PR, I'll take a look and get it in here - I'm sure others would love it!

Great work @Nordes 💯 🍾

**Comment by Nordes** [comment]
https://github.com/MarkPieszak/aspnetcore-Vue-starter/pull/76

Completed
