### ISSUE TITLE
Upgrade vue-loader to 14.2.2

### ISSUE THREAD

**Issue by galczo5** [MarkPieszak/aspnetcore-Vue-starter#86]
Please upgrade package.json from "vue-loader": "^10.0.3" to "vue-loader": "^14.2.2".
14.2.2 uses new loader-utils: https://github.com/babel/babel-loader/issues/392

It caused many problems with vue-i18n-loader.

**Comment by MarkPieszak** [comment]
Thank you I didn't know, let me add that in there! :+1:

**Comment by xShivan** [comment]
Thank you very much for solving this one! We've spent a few hours with @galczo5 trying to solve this issue.
