### ISSUE TITLE
aspnetcore-Vue-starter blank page on start up

### ISSUE THREAD

**Issue by tahirk-atos** [MarkPieszak/aspnetcore-Vue-starter#91]
Hi followed your steps for the aspnetcore-Vue-starter starter app using VS Code and was able to successfully get the template from nuget, select vuejs as the chosen app and then confirmed the .NET Core components were restored and performed an npm install to get the required packages.

When I issued the command "dotnet run" and then clicked on the URL that was displayed in the terminal window I got a blank page in Google Chrome.  Inspecting the Chrome Console I discovered the app had not started up properly various resources were missing.

I then opened the app solution in Visual Studio 2017, did compile and build and then ran it and worked fine the correct page showed up.  Finally reopened the folder in VS Code and typed dotnet run again in the terminal and it worked this time.

Using latest version of VS Code in a 64 bit Windows 10 Professional laptop (VS 2017, git bash, node.js installed).

**Comment by ErikWitkowski** [comment]
You are probably missing the command: npm run build

**Comment by tahirk-atos** [comment]
Thanks Erik will give it a go.

**Comment by MarkPieszak** [comment]
Let us know if that doesn't solve your issue, it sounds like that's all your missing!
