### ISSUE TITLE
[Feat] Update to latest ASP.NET Core 2.1

### ISSUE THREAD

**Issue by MarkPieszak** [MarkPieszak/aspnetcore-Vue-starter#94]

**Comment by mikaelsnavy** [comment]
I'm taking a look at this!

**Comment by mikaelsnavy** [comment]
@MarkPieszak I think I have this done. I'll submit a pull request, lmk if you have any questions. :dancer:

**Comment by tuath** [comment]
Wow, was going to help on this but seems it's already done. When it's merged i can test right away, starting a new project with vue and 2.1...

**Comment by mikaelsnavy** [comment]
@tuath feel free to try it here and let me know if you have issues 

https://github.com/mikaelsnavy/aspnetcore-Vue-starter

**Comment by MarkPieszak** [comment]
Merged it into master! Thank you for the help @mikaelsnavy 🙏 👍 💯 
https://github.com/MarkPieszak/aspnetcore-Vue-starter/commit/1bd2e0efcfa0337f037e159f679d5e2ee4179e4a
