### ISSUE TITLE
Visual studio 2017 - .vue files extension errors

### ISSUE THREAD

**Issue by emadknolg** [MarkPieszak/aspnetcore-Vue-starter#99]
Hello, thank you for you asp.net vue starter 

When I'm trying to open the solution with vs 2017, there are many errors appears. It looks like that vs can't recognize .vue files

what can I do to solve this problem?  

![image](https://user-images.githubusercontent.com/40920508/43364977-6ff7343c-932d-11e8-865d-f27e56ff0816.png)

**Comment by witoong623** [comment]
Try install [Vue.js Pack 2017](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VuejsPack-18329) extension to Visual Studio.

**Comment by MarkPieszak** [comment]
Thanks for answering this one @witoong623 !
